# Generated by Django 3.1.5 on 2021-01-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shopping_cart', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.shoppingcart'),
        ),
    ]
