# Generated by Django 3.1.5 on 2021-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_auto_20210125_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
