# Generated by Django 3.1.5 on 2021-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_auto_20210125_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
